### ISSUE TITLE
Bug: CLI app installation command described in Readme does not work as expected

### ISSUE THREAD

**Issue by mehdiyevcs** [egasimov/aznum2words#9]
**Description**
Installing the CLI application using the provided command does not work as expected. The command must specify a package that points to the cli, not the executable file.

Current:
`go install github.com/egasimov/aznum2words/cmd/cliapp/aznum2words-cli@latest`

Should be: 
`go install github.com/egasimov/aznum2words/cmd/cliapp@latest`

In order for the command to work as expected the name of the cli app package also needs to be changed. 

**To Reproduce**
1. Execute the following command: 
`go install github.com/egasimov/aznum2words/cmd/cliapp/aznum2words-cli@latest`

2. Result: 
`go: github.com/egasimov/aznum2words/cmd/cliapp/aznum2words-cli@latest: module github.com/egasimov/aznum2words@latest found (v0.1.0), but does not contain package github.com/egasimov/aznum2words/cmd/cliapp/aznum2words-cli`

**Expected behavior**
The command installed the binaries into $GOPATH/bin properly, and command should work with provided examples.

**Desktop:**
 - MacOS Monterey 12.2
 - Go version go1.19.4

**Comment by egasimov** [comment]
@mehdiyevcs Thank you for providing this information. It seems like there is an issue with the command provided to install the CLI application. 

I appreciate your help in fixing this issue. Let me know if you have any questions or need further assistance.

**Comment by mehdiyevcs** [comment]
Thanks for the quick response @egasimov!
Find the PR fix below. Please review.
https://github.com/egasimov/aznum2words/pull/10

**Comment by egasimov** [comment]
Good job! 
merged to master branch and released with [v0.1.1](https://github.com/egasimov/aznum2words/releases/tag/v0.1.1)
